CREATE TABLE games (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	is_public BOOLEAN NOT NULL DEFAULT TRUE,
	shorthand TEXT NOT NULL UNIQUE,
	pishtov_version TEXT NOT NULL,
	uploader_ip TEXT NOT NULL,
	upload_date TIMESTAMP NOT NULL
);

CREATE TABLE files (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content BYTEA NOT NULL
);
CREATE UNIQUE INDEX unique_file_content on files(MD5(content));


CREATE TABLE games_files (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	filename VARCHAR(255) NOT NULL,
	file_contents_hash CHAR(32) NOT NULL,
	game_id INTEGER NOT NULL,
	FOREIGN KEY (game_id) REFERENCES games (id)
);

CREATE TABLE framework_files (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	framework_name TEXT NOT NULL,
	-- 255 is the maximum rel. path + file
	filename VARCHAR(255) NOT NULL,
	file_contents_hash CHAR(32) NOT NULL
);

