curl 'http://localhost:3114/upload/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDOF9leEeOPZvfyNQ' \
  -H 'Accept: */*' \
  -H 'Sec-GPC: 1' \
  -H 'Origin: http://localhost:3114' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3114/upload' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw $'------WebKitFormBoundaryDOF9leEeOPZvfyNQ\r\nContent-Disposition: form-data; name="textarea"\r\n\r\nthis is a test from textarea\r\n------WebKitFormBoundaryDOF9leEeOPZvfyNQ\r\nContent-Disposition: form-data; name="file"\r\n\r\nundefined\r\n------WebKitFormBoundaryDOF9leEeOPZvfyNQ\r\nContent-Disposition: form-data; name="obfuscate"\r\n\r\nfalse\r\n------WebKitFormBoundaryDOF9leEeOPZvfyNQ\r\nContent-Disposition: form-data; name="public"\r\n\r\ntrue\r\n------WebKitFormBoundaryDOF9leEeOPZvfyNQ--\r\n' \
  --compressed
